"""
Generate Activity Logs Feature Documentation — Word (.docx)
Mirrors the content of Activity_Logs_Full_Documentation.pdf exactly.
Diagrams are reused from _diagram_imgs/ (generated by the PDF script).
Run the PDF generator first to populate the diagram images, then run this.
"""

import os
import sys

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

OUT_DIR  = os.path.dirname(os.path.abspath(__file__))
IMG_DIR  = os.path.join(OUT_DIR, "_diagram_imgs")
APIG_DIR = os.path.join(OUT_DIR, "_api_gw_imgs")
DOCX_PATH = os.path.join(OUT_DIR, "Activity_Logs_Full_Documentation.docx")

# ── Colour helpers ────────────────────────────────────────────────────────────
def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))

HDR_BG   = "1a1a2e"
HDR_FG   = "FFFFFF"
ROW1_BG  = "f8f9fa"
ROW2_BG  = "FFFFFF"
ACCENT   = "16213e"
CODE_BG  = "f0f0f0"

# ── Low-level XML helpers ─────────────────────────────────────────────────────
def set_cell_bg(cell, hex_color):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  hex_color.lstrip("#"))
    tcPr.append(shd)

def set_cell_borders(cell, color="dee2e6", sz="4"):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = OxmlElement("w:tcBorders")
    for side in ("top", "left", "bottom", "right"):
        el = OxmlElement(f"w:{side}")
        el.set(qn("w:val"),   "single")
        el.set(qn("w:sz"),    sz)
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), color.lstrip("#"))
        tcBorders.append(el)
    tcPr.append(tcBorders)

def para_in_cell(cell, text, bold=False, italic=False, font_size=9,
                 color=None, code=False, align=WD_ALIGN_PARAGRAPH.LEFT):
    cell.paragraphs[0].clear()
    p   = cell.paragraphs[0]
    p.alignment = align
    run = p.add_run(text)
    run.bold   = bold
    run.italic = italic
    run.font.size = Pt(font_size)
    if code:
        run.font.name = "Courier New"
    if color:
        r, g, b = hex_to_rgb(color)
        run.font.color.rgb = RGBColor(r, g, b)
    return p

# ── Document-level style helpers ─────────────────────────────────────────────
def add_heading(doc, text, level=1):
    p = doc.add_heading(text, level=level)
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    return p

def add_body(doc, text):
    p = doc.add_paragraph(text)
    p.style = doc.styles["Normal"]
    p.paragraph_format.space_after = Pt(6)
    return p

def add_bullet(doc, text):
    p = doc.add_paragraph(style="List Bullet")
    # Support simple bold markers **text**
    parts = text.split("**")
    for i, part in enumerate(parts):
        run = p.add_run(part)
        run.bold = (i % 2 == 1)
    p.paragraph_format.space_after = Pt(3)
    return p

def add_code(doc, text):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.name = "Courier New"
    run.font.size = Pt(8)
    p.paragraph_format.left_indent = Cm(0.5)
    p.paragraph_format.space_after = Pt(4)
    return p

def add_caption(doc, text):
    p = doc.add_paragraph(text)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.runs[0] if p.runs else p.add_run(text)
    run.italic = True
    run.font.size = Pt(8)
    p.paragraph_format.space_after = Pt(8)
    return p

def add_hr(doc):
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"),   "single")
    bottom.set(qn("w:sz"),    "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "1a1a2e")
    pBdr.append(bottom)
    pPr.append(pBdr)
    p.paragraph_format.space_after = Pt(4)

def add_image(doc, img_prefix, caption, width=Inches(6.0)):
    # Files are named like 01_role_hierarchy.png — match by numeric prefix
    import glob
    matches = sorted(glob.glob(os.path.join(IMG_DIR, f"{img_prefix}_*.png")))
    if not matches:
        # Fallback: exact name
        matches = [os.path.join(IMG_DIR, f"{img_prefix}.png")]
    path = matches[0]
    if os.path.exists(path):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run()
        run.add_picture(path, width=width)
    else:
        doc.add_paragraph(f"[Diagram not found: {img_prefix}]")
    add_caption(doc, caption)

def add_image_path(doc, path, caption, width=Inches(6.0)):
    """Embed an image from a full file path."""
    if os.path.exists(path):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run()
        run.add_picture(path, width=width)
    else:
        doc.add_paragraph(f"[Image not found: {os.path.basename(path)}]")
    add_caption(doc, caption)

# ── Generic table builder ─────────────────────────────────────────────────────
def add_table(doc, data, col_widths_cm, hdr_bg=HDR_BG, row1_bg=ROW1_BG):
    """data[0] = header row, data[1:] = body rows."""
    t = doc.add_table(rows=len(data), cols=len(data[0]))
    t.alignment = WD_TABLE_ALIGNMENT.LEFT
    t.style = "Table Grid"

    for r_idx, row_data in enumerate(data):
        row = t.rows[r_idx]
        is_hdr = (r_idx == 0)
        bg = hdr_bg if is_hdr else (row1_bg if r_idx % 2 == 1 else ROW2_BG)

        for c_idx, cell_text in enumerate(row_data):
            cell = row.cells[c_idx]
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER

            # Width
            if c_idx < len(col_widths_cm):
                cell.width = Cm(col_widths_cm[c_idx])

            set_cell_bg(cell, bg)
            set_cell_borders(cell)

            text_color = HDR_FG if is_hdr else None
            bold       = is_hdr
            code       = False
            para_in_cell(cell, str(cell_text), bold=bold,
                         font_size=8 if is_hdr else 8,
                         color=text_color, code=code)

    doc.add_paragraph()  # spacing after table
    return t


# ══════════════════════════════════════════════════════════════════════════════
# BUILD DOCUMENT
# ══════════════════════════════════════════════════════════════════════════════
def build_docx():
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin   = Cm(2.5)
        section.right_margin  = Cm(2.5)

    # ── COVER ────────────────────────────────────────────────────────────────
    doc.add_paragraph()
    title = doc.add_paragraph("Activity Logs Feature")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.runs[0].bold = True
    title.runs[0].font.size = Pt(26)
    title.runs[0].font.color.rgb = RGBColor(26, 26, 46)

    sub = doc.add_paragraph("Full Technical Documentation")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.size = Pt(14)

    add_hr(doc)

    for line in [
        "Project: Fideon OS Platform",
        "Feature: Audit Trail & Activity Log System",
        "Roles Covered: global_admin · admin · user · viewer · guest",
        "Date: 2026-03-16",
    ]:
        p = doc.add_paragraph(line)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p.runs[0].font.size = Pt(11)

    doc.add_paragraph()
    add_image(doc, "01", "Figure 1 — Role Hierarchy Overview")
    doc.add_page_break()

    # ── SECTION 1: OVERVIEW ──────────────────────────────────────────────────
    add_heading(doc, "1. Feature Overview", 1)
    add_hr(doc)
    add_body(doc,
        "The Activity Logs system provides a tamper-evident, role-scoped audit trail "
        "of all significant actions taken across the Fideon OS platform. It is built on "
        "two Supabase PostgreSQL tables (auth_audit and audit_logs), enforced by PostgreSQL "
        "Row-Level Security (RLS) policies, and surfaced to users via the /activity frontend page."
    )
    add_heading(doc, "Core Design Principles", 2)
    add_bullet(doc, "**Tamper-Evidence:** Each auth_audit row stores a SHA-256 integrity_hash computed from non-PII fields. Any post-write modification invalidates the hash.")
    add_bullet(doc, "**Privacy (PII Protection):** The email field is stored in the row but deliberately excluded from the integrity hash. Backend server logs use PII scrubbing for fields like password, token, email, phone, ssn.")
    add_bullet(doc, "**Least Privilege:** Each role sees only what they are authorized to see via RLS policies. Users see only their own rows; admins see their org; global_admin sees all.")
    add_bullet(doc, "**ATNA Compliance:** Action codes (C/R/U/D/E) and outcome codes (0/4/8/12) follow the ATNA healthcare audit standard.")
    add_bullet(doc, "**Immutability:** Audit rows are protected by PostgreSQL BEFORE UPDATE / BEFORE DELETE triggers (prevent_audit_modification()) that raise an exception for any modification attempt — including service_role and direct DB connections. Enforces EU AI Act Art.12, SOC2 CC7.2, and NAIC compliance.")
    doc.add_page_break()

    # ── SECTION 2: ROLES ─────────────────────────────────────────────────────
    add_heading(doc, "2. Role Definitions & Hierarchy", 1)
    add_hr(doc)
    add_body(doc,
        "The platform uses a five-tier role model stored as a PostgreSQL enum (app_role) "
        "and managed through the user_roles table. Only global_admin can assign or change roles."
    )
    roles_data = [
        ["Role", "Colour", "Can Assign Roles", "Sees All Audit Logs", "Description"],
        ["global_admin", "Red",    "YES", "YES", "Full platform control. Assigns/changes all roles."],
        ["admin",        "Orange", "NO",  "YES", "Manages users and pods within their scope."],
        ["user",         "Green",  "NO",  "Own only", "Standard authenticated user."],
        ["viewer",       "Blue",   "NO",  "Own only", "Read-only access to permitted resources."],
        ["guest",        "Grey",   "NO",  "Own only (DB-level)", "Most restricted. No /activity frontend page (route guard blocks). However the 'Users see own' RLS policy applies to all authenticated users — guest CAN query own auth_audit and audit_logs rows directly via the Supabase SDK. Frontend UI is the only blocked layer (intentional design: permissive at DB, restricted at UI)."],
    ]
    add_table(doc, roles_data, col_widths_cm=[3.2, 2.2, 2.8, 3.5, 5.3])
    add_image(doc, "01", "Figure 2 — Role Hierarchy with Promotion Paths")
    doc.add_page_break()

    # ── SECTION 3: ER DIAGRAM ────────────────────────────────────────────────
    add_heading(doc, "3. Entity-Relationship (ER) Diagram", 1)
    add_hr(doc)
    add_body(doc,
        "The diagram below shows all seven database tables and their relationships. "
        "The auth_audit and audit_logs tables both reference auth.users via user_id. "
        "Device-related logs are linked to the devices table."
    )
    add_image(doc, "02", "Figure 3 — Full Entity-Relationship Diagram")
    doc.add_page_break()

    # ── SECTION 4: SCHEMA ────────────────────────────────────────────────────
    add_heading(doc, "4. Database Schema — Column-Level Detail", 1)
    add_hr(doc)
    add_body(doc,
        "Detailed column specifications for the two primary audit tables and the role "
        "assignment table, including data types, constraints, and descriptions."
    )
    add_image(doc, "03", "Figure 4 — Schema Column Detail Diagram")

    add_heading(doc, "4.1 auth_audit — SQL Definition", 2)
    add_code(doc,
        "CREATE TABLE public.auth_audit (\n"
        "  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n"
        "  user_id        UUID        NOT NULL REFERENCES auth.users(id),\n"
        "  email          TEXT,\n"
        "  role           TEXT,\n"
        "  event          TEXT,\n"
        "  action_code    TEXT,       -- ATNA: C/R/U/D/E\n"
        "  outcome_code   INTEGER,    -- ATNA: 0/4/8/12\n"
        "  resource_type  TEXT,\n"
        "  resource_id    TEXT,\n"
        "  integrity_hash TEXT,       -- SHA-256 tamper-evidence\n"
        "  created_at     TIMESTAMPTZ DEFAULT now()\n"
        ");"
    )

    add_heading(doc, "4.2 audit_logs — SQL Definition", 2)
    add_code(doc,
        "CREATE TABLE public.audit_logs (\n"
        "  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),\n"
        "  user_id        UUID        REFERENCES auth.users(id),\n"
        "  action         TEXT        NOT NULL,\n"
        "  resource_type  TEXT        NOT NULL,\n"
        "  resource_id    TEXT,\n"
        "  details        JSONB,\n"
        "  previous_value JSONB,      -- before-state, PII-scrubbed (migration 20260316000002)\n"
        "  new_value      JSONB,      -- after-state,  PII-scrubbed (migration 20260316000002)\n"
        "  ip_address     TEXT,\n"
        "  user_agent     TEXT,\n"
        "  integrity_hash TEXT,       -- SHA-256 tamper-evidence  (migration 20260316000001)\n"
        "  created_at     TIMESTAMPTZ DEFAULT now()\n"
        ");\n"
        "CREATE INDEX idx_audit_logs_user_id       ON public.audit_logs (user_id);\n"
        "CREATE INDEX idx_audit_logs_resource_type ON public.audit_logs (resource_type);\n"
        "CREATE INDEX idx_audit_logs_resource_id   ON public.audit_logs (resource_id) WHERE resource_id IS NOT NULL;\n"
        "CREATE INDEX idx_audit_logs_created_at    ON public.audit_logs (created_at DESC);"
    )
    doc.add_page_break()

    # ── SECTION 5: RLS ───────────────────────────────────────────────────────
    add_heading(doc, "5. Row-Level Security (RLS) Policies", 1)
    add_hr(doc)
    add_body(doc,
        "All audit tables have RLS enabled. The policies enforce that each role can only "
        "access the rows it is authorized to see. There are no UPDATE or DELETE policies and "
        "additionally, database-level BEFORE UPDATE / BEFORE DELETE triggers "
        "(prevent_audit_modification()) make audit records truly immutable — even service_role "
        "and direct Postgres connections cannot modify rows. The has_role(uid, 'admin') helper "
        "function is hierarchical and returns true for both admin and global_admin, so "
        "global_admin retains full access to device logs and audit_logs via those policies."
    )
    add_image(doc, "04", "Figure 5 — RLS Policy Decision Flow")
    rls_data = [
        ["Table", "Policy Name", "Operation", "Who", "Condition"],
        ["auth_audit",        "Users insert own",       "INSERT", "Any auth user",  "auth.uid() = user_id"],
        ["auth_audit",        "Users see own",                    "SELECT", "user/viewer/guest ¹", "user_id = auth.uid()"],
        ["auth_audit",        "Admins see all except global_admin", "SELECT", "admin",              "role IN ('admin','user','viewer','guest')"],
        ["auth_audit",        "Global admins see all",  "SELECT", "global_admin",   "No restriction"],
        ["audit_logs",        "System can insert",      "INSERT", "Any",            "true"],
        ["audit_logs",        "Users see own",          "SELECT", "Any",            "auth.uid() = user_id"],
        ["audit_logs",        "Admins view all",        "SELECT", "admin/global",   "has_role(uid,'admin') [hierarchical]"],
        ["device_sync_logs",  "Admins only view",       "SELECT", "admin/global",   "has_role(uid,'admin') [hierarchical]"],
        ["device_usage_logs", "Admins only view",       "SELECT", "admin/global",   "has_role(uid,'admin') [hierarchical]"],
    ]
    add_table(doc, rls_data, col_widths_cm=[3.2, 4.5, 2.2, 2.8, 4.5])
    add_body(doc,
        "¹ Guest & 'Users see own': The policy has no role restriction — the condition "
        "user_id = auth.uid() applies to ALL authenticated users including guest. "
        "Guest can therefore query their own auth_audit and audit_logs rows at the DB level. "
        "The /activity frontend page is blocked by the route guard for UX reasons, not by RLS. "
        "Design intent: permissive at DB, restricted at UI layer."
    )
    doc.add_page_break()

    # ── SECTION 6: DATA FLOW ─────────────────────────────────────────────────
    add_heading(doc, "6. Data Flow — How Logs Are Created", 1)
    add_hr(doc)
    add_body(doc,
        "Every audit row follows a five-step pipeline: the user triggers an action in the "
        "frontend, the relevant component captures the event, auditHash.ts computes a SHA-256 "
        "integrity hash, the Supabase RLS INSERT policy validates the caller, and finally "
        "the row is persisted in the auth_audit table."
    )
    add_image(doc, "05", "Figure 6 — Audit Data Flow with Swim Lanes")
    doc.add_page_break()

    # ── SECTION 7: SEQUENCES ─────────────────────────────────────────────────
    add_heading(doc, "7. Sequence Diagrams", 1)
    add_hr(doc)

    add_heading(doc, "7.1 Login Audit Event", 2)
    add_body(doc,
        "When a user successfully signs in, Auth.tsx immediately captures the timestamp, "
        "calls auditHash.ts to compute the integrity hash, then inserts a login event row "
        "into auth_audit."
    )
    add_image(doc, "06", "Figure 7 — Login Audit Sequence")

    add_heading(doc, "7.2 Admin Approves Pod Activation", 2)
    add_body(doc,
        "When an admin clicks Approve on a pod request, the component first updates the "
        "pod_activation_requests table, then computes the audit hash and writes an "
        "approve_pod:{model_id} event to auth_audit."
    )
    add_image(doc, "07", "Figure 8 — Admin Approve Pod Sequence")
    doc.add_page_break()

    add_heading(doc, "7.3 Viewing Activity Logs", 2)
    add_body(doc,
        "When any authenticated user navigates to /activity, Activity.tsx issues a SELECT "
        "query. The Supabase RLS layer automatically filters rows based on the caller's role — "
        "global_admin sees all, admin sees most (all except global_admin rows), user/viewer "
        "sees only their own rows. Guest receives 0 rows through the frontend (route guard "
        "blocks the /activity page) but CAN read own rows at the DB level via the 'Users see "
        "own' RLS policy — the frontend is the restriction layer, not RLS."
    )
    add_image(doc, "08", "Figure 9 — View Activity Logs Sequence")
    doc.add_page_break()

    # ── SECTION 8: HASH ──────────────────────────────────────────────────────
    add_heading(doc, "8. Audit Integrity Hash — Tamper Evidence", 1)
    add_hr(doc)
    add_body(doc,
        "Every row in auth_audit includes an integrity_hash field computed using SHA-256 "
        "via the Web Crypto API (crypto.subtle.digest). The hash is computed from eight "
        "non-PII fields. The email field is deliberately excluded from the hash to protect "
        "personally identifiable information."
    )
    add_image(doc, "09", "Figure 10 — Integrity Hash Computation & Verification")

    add_heading(doc, "Hash Input Fields", 2)
    for f in [
        "user_id — the UUID of the acting user",
        "role — the user's role at time of action",
        "event — the event name (login, logout, approve_pod, etc.)",
        "action_code — ATNA action code (C/R/U/D/E)",
        "outcome_code — ATNA outcome code (0/4/8/12)",
        "resource_type — resource category (auth_session, pod_activation)",
        "resource_id — specific resource identifier (nullable: null for login/logout events)",
        "previous_value — before-state JSON, PII-scrubbed (audit_logs only)",
        "new_value — after-state JSON, PII-scrubbed (audit_logs only)",
        "created_at — ISO 8601 timestamp",
    ]:
        add_bullet(doc, f)
    add_body(doc, "Excluded from hash: email (PII — stored in row but not hashed)")
    doc.add_page_break()

    # ── SECTION 9: COMPONENTS ────────────────────────────────────────────────
    add_heading(doc, "9. Frontend Component Architecture", 1)
    add_hr(doc)
    add_body(doc,
        "The frontend is a React/TypeScript single-page application. Role detection is "
        "centralized in the useUserRole hook. All audit writes flow through auditHash.ts. "
        "Route protection is enforced by ProtectedRoute.tsx."
    )
    add_image(doc, "10", "Figure 11 — Frontend Component Architecture Diagram")
    doc.add_page_break()

    # ── SECTION 10: ACCESS MATRIX ────────────────────────────────────────────
    add_heading(doc, "10. Access Control Matrix", 1)
    add_hr(doc)
    add_body(doc,
        "The matrix below provides a complete overview of which roles can perform which "
        "operations across the activity logs system and related features."
    )
    add_image(doc, "11", "Figure 12 — Full Access Control Matrix")

    add_heading(doc, "Detailed Access Matrix", 2)
    matrix_data = [
        ["Data Scope",                              "global_admin", "admin",  "user",    "viewer",  "guest"],
        ["Access /activity page (UI)",              "YES",          "YES",    "YES",     "YES",     "NO (route guard)"],
        ["Own auth_audit rows (DB via RLS)",        "YES",          "YES",    "YES",     "YES",     "YES ¹"],
        ["Own audit_logs rows (DB via RLS)",        "YES",          "YES",    "YES",     "YES",     "YES ¹"],
        ["All user role rows",                      "YES",          "YES",    "NO",      "NO",      "NO"],
        ["All admin role rows",                     "YES",          "YES ²",  "NO",      "NO",      "NO"],
        ["All viewer role rows",                    "YES",          "YES",    "NO",      "NO",      "NO"],
        ["All guest role rows",                     "YES",          "YES",    "NO",      "NO",      "NO"],
        ["global_admin role rows",                  "YES",          "NO",     "NO",      "NO",      "NO"],
        ["All audit_logs rows",                     "YES",          "YES",    "NO",      "NO",      "NO"],
        ["device_sync_logs",                        "YES",          "YES",    "NO",      "NO",      "NO"],
        ["device_usage_logs",                       "YES",          "YES",    "NO",      "NO",      "NO"],
    ]
    add_table(doc, matrix_data, col_widths_cm=[5.5, 2.2, 2.2, 2.0, 2.0, 3.3])
    add_body(doc,
        "¹ Guest DB-level access (intentional design): The RLS policy 'Users see own' "
        "evaluates user_id = auth.uid() for ALL authenticated users — there is no role "
        "restriction in the policy condition. Guest users CAN read their own auth_audit "
        "and audit_logs rows directly via the Supabase SDK or API. The /activity frontend "
        "page is blocked by the route guard (UX/product decision), not by RLS. "
        "This is an intentional permissive-at-DB, restricted-at-UI design."
    )
    add_body(doc,
        "² Cross-admin visibility (intentional by design): An admin can read the full "
        "audit trail of OTHER admins within the same tenant. The RLS condition "
        "role IN ('admin','user','viewer','guest') includes all admin rows. This is "
        "deliberate — it ensures accountability: any admin action is visible to peer "
        "admins and to global_admin. This is NOT a privilege escalation: admins cannot "
        "see global_admin rows, and no UPDATE/DELETE policy exists so audit rows are "
        "immutable to all roles."
    )
    doc.add_page_break()

    # ── SECTION 11: EVENTS ───────────────────────────────────────────────────
    add_heading(doc, "11. Event Types & ATNA Codes", 1)
    add_hr(doc)
    add_body(doc,
        "The table below lists all audit event types currently implemented, along with "
        "the ATNA-standard action and outcome codes, and the resource types they apply to."
    )
    add_image(doc, "12", "Figure 13 — Event Types & ATNA Codes Reference")

    add_heading(doc, "Event Types Table", 2)
    event_data = [
        ["Event", "Description", "Actor", "action_code", "outcome_code", "resource_type"],
        ["login",                  "Successful sign-in",     "Any",          "E", "0", "auth_session"],
        ["login_failed",           "Failed sign-in attempt", "Any",          "E", "8", "auth_session"],
        ["logout",                 "Sign-out click",         "Any",          "E", "0", "auth_session"],
        ["approve_pod:{model_id}", "Admin approves pod",     "admin/global", "U", "0", "pod_activation"],
        ["reject_pod:{model_id}",  "Admin rejects pod",      "admin/global", "U", "0", "pod_activation"],
    ]
    add_table(doc, event_data, col_widths_cm=[4.2, 3.5, 2.5, 2.0, 2.2, 3.5])

    add_heading(doc, "ATNA Action Code Reference", 2)
    atna_data = [
        ["Code", "Meaning", "Status", "Used By"],
        ["C", "Create", "Planned — no events assigned yet", "Reserved for future: e.g. user creation events"],
        ["R", "Read",   "Planned — no events assigned yet", "Reserved for future: e.g. document view events"],
        ["U", "Update", "Active",                           "approve_pod:{model_id}, reject_pod:{model_id}"],
        ["D", "Delete", "Planned — no events assigned yet", "Reserved for future: e.g. record deletion events"],
        ["E", "Execute","Active",                           "login, login_failed, logout"],
    ]
    add_table(doc, atna_data, col_widths_cm=[1.5, 2.5, 4.5, 8.5])
    add_body(doc,
        "Note: Codes C, R, and D are defined per the ATNA standard and reserved for future "
        "use. They are marked 'Planned' to signal no current event uses them — a reader "
        "should not expect to find live rows with these codes."
    )

    add_heading(doc, "ATNA Outcome Code Reference", 2)
    outcome_data = [
        ["Code", "Meaning", "Severity"],
        ["0",  "Success",          "None — operation completed normally"],
        ["4",  "Minor failure",    "Low — minor issue occurred"],
        ["8",  "Serious failure",  "High — significant problem"],
        ["12", "Major failure",    "Critical — severe error"],
    ]
    add_table(doc, outcome_data, col_widths_cm=[1.5, 3.5, 12.0])
    doc.add_page_break()

    # ── SECTION 12: BACKEND LOGGING ──────────────────────────────────────────
    add_heading(doc, "12. Backend Logging Architecture", 1)
    add_hr(doc)
    add_body(doc,
        "In addition to the Supabase-based audit tables, the FastAPI backend implements "
        "structured JSON logging via structlog. A RequestLoggingMiddleware intercepts every "
        "HTTP request, assigns a unique request_id, and logs method, path, client IP, "
        "status code, and duration. Unhandled exceptions are captured at ERROR level with "
        "full traceback (exc_info=True) before being re-raised, so 500s are never invisible. "
        "The log level is configurable via the LOG_LEVEL environment variable (default: INFO). "
        "Log files use a RotatingFileHandler (10 MB per file, 5 backups — 50 MB max on disk), "
        "preventing unbounded disk growth. A two-pass PII scrubbing pipeline protects all log "
        "output — Pass 1 (field-name keywords, sync) runs in the structlog processor chain; "
        "Pass 2 (Microsoft Presidio NLP) runs asynchronously via scrub_text() and a "
        "ThreadPoolExecutor(max_workers=2) so the asyncio event loop is never blocked — see "
        "Section 13 for full detail. A startup warning is emitted if Presidio is unavailable. "
        "An insert_audit_log() helper in backend/app/core/supabase.py is called by all admin "
        "and pod activation routes to write rows into audit_logs with ip_address, user_agent, "
        "previous_value, new_value, and a server-side SHA-256 integrity_hash. Audit writes "
        "are fire-and-forget — failures are silently swallowed so auditing never blocks the "
        "main request path."
    )
    add_image(doc, "13", "Figure 14 — Backend Logging Architecture")
    doc.add_page_break()

    # ── SECTION 13: PII DETECTION ────────────────────────────────────────────
    add_heading(doc, "13. PII Detection — Presidio & Regex", 1)
    add_hr(doc)
    add_body(doc,
        "All log data passes through a two-pass PII scrubbing pipeline before being "
        "written to any output. The pipeline runs in backend/app/logger/__init__.py "
        "(Python/Presidio) and is mirrored in frontend/src/logger/index.ts (TypeScript/regex)."
    )

    add_heading(doc, "Pass 1 — Field-name Keyword Match", 2)
    add_body(doc,
        "Every key in the log payload is compared against a hard-coded set of 20 sensitive "
        "field names (case-insensitive). A match unconditionally replaces the value with "
        "[REDACTED] — regardless of the actual content. Fields covered: password, passwd, "
        "secret, token, api_key, authorization, ssn, social_security, credit_card, "
        "card_number, cvv, dob, date_of_birth, birth_date, full_name, first_name, last_name, "
        "mobile, phone, phone_number, address."
    )

    add_heading(doc, "Pass 2 — Async Content-based PII Detection", 2)
    add_body(doc,
        "After field-name scrubbing, string values can be scanned for PII content — "
        "catching sensitive data inside generic fields like 'message' or 'details' regardless "
        "of the key name. Pass 2 does NOT run inside the sync structlog processor — doing so "
        "would block the asyncio event loop under load. Instead, Pass 2 is exposed as "
        "await scrub_text(value), an async helper that offloads Presidio NLP work to a "
        "dedicated ThreadPoolExecutor(max_workers=2) via loop.run_in_executor(). Call it from "
        "route handlers or middleware whenever you need to log potentially sensitive free-text."
    )
    add_body(doc,
        "On the backend, Microsoft Presidio (presidio-analyzer + presidio-anonymizer) uses a "
        "spaCy English NLP model to detect named entities. Detected entities are replaced with "
        "labelled placeholders such as <PERSON>, <US_SSN>, <CREDIT_CARD>. Email addresses are "
        "pre-masked to u***@domain format before the Presidio scan. If Presidio or the spaCy "
        "model is unavailable, _PRESIDIO_AVAILABLE is set to False, a startup warning is "
        "logged, and the system degrades gracefully to Pass 1 only — no exception is raised."
    )
    add_body(doc,
        "On the frontend, contentScrubString() applies regex-based PII_PATTERNS that mirror "
        "Presidio entity labels, producing identical <ENTITY_TYPE> replacements. No ML model "
        "is required — the patterns run in-browser or in Node.js with zero additional dependencies."
    )

    pii_data = [
        ["Entity Type",   "Example Input",           "Replacement",      "Backend",               "Frontend"],
        ["PERSON",        "John Smith",              "<PERSON>",         "Presidio NLP",          "—"],
        ["EMAIL_ADDRESS", "user@example.com",        "u***@example.com", "Email mask + Presidio", "Email mask + regex"],
        ["PHONE_NUMBER",  "+1 (555) 123-4567",       "<PHONE_NUMBER>",   "Presidio NLP",          "Regex"],
        ["CREDIT_CARD",   "4111 1111 1111 1111",     "<CREDIT_CARD>",    "Presidio NLP",          "Regex"],
        ["US_SSN",        "123-45-6789",             "<US_SSN>",         "Presidio NLP",          "Regex"],
        ["IBAN_CODE",     "GB29NWBK60161331926819",  "<IBAN_CODE>",      "Presidio NLP",          "Regex"],
        ["LOCATION",      "New York, NY",            "<LOCATION>",       "Presidio NLP",          "—"],
        ["IP_ADDRESS",    "192.168.1.1",             "(kept — forensic)","Intentionally excluded", "—"],
    ]
    add_table(doc, pii_data, col_widths_cm=[3.2, 4.0, 3.8, 3.8, 2.2])

    add_heading(doc, "Backend Installation", 3)
    add_code(doc,
        "pip install presidio-analyzer presidio-anonymizer spacy\n"
        "python -m spacy download en_core_web_sm\n\n"
        "# Or via requirements.txt:\n"
        "# presidio-analyzer>=2.2.0\n"
        "# presidio-anonymizer>=2.2.0\n"
        "# spacy>=3.4.0,<4.0.0\n"
        "# structlog>=23.1.0,<25.0.0\n"
        "# en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/..."
    )
    add_image(doc, "14", "Figure 15 — PII Scrubbing Pipeline (Two-Pass Architecture)")
    doc.add_page_break()

    # ── SECTION 14: FILE REFERENCE ───────────────────────────────────────────
    add_heading(doc, "14. File Reference", 1)
    add_hr(doc)
    add_body(doc, "Key source files implementing the Activity Logs feature:")
    file_data = [
        ["Category",      "File Path",                                                                       "Purpose"],
        ["DB Migration",  "supabase/migrations/20260313091500_auth_audit_logs.sql",                          "auth_audit table + RLS policies"],
        ["DB Migration",  "supabase/migrations/20251116145514_03b8c065-31f2-46c1-a062-a1f2e4363a04.sql",     "audit_logs table + RLS policies"],
        ["DB Migration",  "supabase/migrations/20260312193000_fnf9_schema_closure.sql",                      "Role enum + user_roles + roles tables"],
        ["DB Migration",  "supabase/migrations/20260312194000_fnf10_rls_hardening.sql",                      "RLS hardening pass"],
        ["DB Migration",  "supabase/migrations/20260316000000_auth_audit_user_id_fk.sql",                    "FK constraint auth_audit.user_id -> auth.users(id)"],
        ["DB Migration",  "supabase/migrations/20260316000001_audit_immutability.sql",                       "Immutability triggers + integrity_hash on audit_logs + archive tables"],
        ["DB Migration",  "supabase/migrations/20260316000002_audit_logs_change_tracking.sql",               "previous_value + new_value JSONB columns + resource_id index on audit_logs"],
        ["Frontend Page", "frontend/src/app-pages/Activity.tsx",                                             "Activity log UI page"],
        ["Frontend Lib",  "frontend/src/lib/auditHash.ts",                                                   "SHA-256 integrity hash utility"],
        ["Frontend Page", "frontend/src/app-pages/Auth.tsx",                                                 "Login/login_failed audit writer (resource_id: null)"],
        ["Frontend Comp", "frontend/src/components/Layout.tsx",                                              "Logout audit event writer (resource_id: null)"],
        ["Frontend Comp", "frontend/src/components/admin/PodActivationRequests.tsx",                        "Pod approve/reject audit"],
        ["Frontend Comp", "frontend/src/components/AppSidebar.tsx",                                         "Role-filtered navigation"],
        ["Frontend Hook", "frontend/src/hooks/useUserRole.ts",                                              "Role detection hook"],
        ["Backend",       "backend/app/core/supabase.py",                                                   "insert_audit_log() helper (ip_address, user_agent, integrity_hash, previous_value, new_value)"],
        ["Backend",       "backend/app/routes/admin.py",                                                    "Admin API endpoints + create_user/set_role audit calls"],
        ["Backend",       "backend/app/routes/pod_activation.py",                                           "Pod activation endpoints + approve/reject/allocate audit calls"],
        ["Backend",       "backend/app/logger/__init__.py",                                                 "Structured request logging + two-pass Presidio PII scrubber"],
        ["Backend",       "backend/requirements.txt",                                                       "presidio-analyzer, presidio-anonymizer, spacy, en-core-web-sm"],
        ["Frontend",      "frontend/src/logger/index.ts",                                                   "Pino logger + two-pass PII scrubber (field-name + regex content scan)"],
    ]
    add_table(doc, file_data, col_widths_cm=[3.0, 8.0, 6.0])
    doc.add_page_break()

    # ── SECTION 15: COMPLIANCE ───────────────────────────────────────────────
    add_heading(doc, "15. Compliance & Immutability", 1)
    add_hr(doc)
    add_body(doc,
        "The Activity Logs system is designed to meet the audit trail requirements of "
        "EU AI Act (Art. 12/13), SOC2 (CC7.2/CC9.1), and NAIC AI Bulletin. "
        "The following mechanisms are in place:"
    )

    add_heading(doc, "15.1 Database-Level Immutability", 2)
    add_body(doc,
        "Migration 20260316000001_audit_immutability.sql installs four BEFORE UPDATE / "
        "BEFORE DELETE triggers on both auth_audit and audit_logs. The trigger function "
        "prevent_audit_modification() raises a P0001 exception for any modification attempt. "
        "This fires regardless of RLS bypass — service_role, backend calls, and direct "
        "Postgres connections are all blocked. Only a superuser running "
        "ALTER TABLE ... DISABLE TRIGGER can circumvent this, and that action is itself "
        "logged by Postgres."
    )
    add_body(doc, "Verified behavior in Supabase SQL Editor (role: postgres):")
    add_code(doc, "UPDATE public.auth_audit SET event = 'tampered' WHERE id = (...);")
    add_body(doc,
        "Result: ERROR P0001: Audit log records are immutable "
        "(EU AI Act Art.12 / SOC2 CC7.2 / NAIC). "
        'Operation "UPDATE" on table "auth_audit" is not permitted.'
    )

    add_heading(doc, "15.2 Integrity Hash Coverage", 2)
    add_body(doc,
        "Both audit tables now carry integrity_hash (SHA-256). "
        "For auth_audit: computed in auditHash.ts (frontend, Web Crypto API) over 8 non-PII "
        "fields before insert. For audit_logs: computed in insert_audit_log() (backend, Python "
        "hashlib) over user_id, action, resource_type, resource_id, previous_value, new_value, "
        "and created_at before insert. Email and other PII are excluded from both hashes."
    )

    add_heading(doc, "15.3 IP Address & User Agent Capture", 2)
    add_body(doc,
        "All backend-initiated audit writes (admin actions, pod approvals/rejections, model "
        "allocations) populate ip_address from request.client.host and user_agent from the "
        "HTTP request header. This provides a complete forensic trail for regulatory review."
    )

    add_heading(doc, "15.4 Retention Policy", 2)
    add_body(doc,
        "EU AI Act requires logs retained for a minimum of 6 months; SOC2 and NAIC require "
        "12 months. The following architecture is implemented via pg_cron (enabled in Supabase):"
    )
    add_bullet(doc, "audit_logs_archive and auth_audit_archive tables mirror the live tables with identical immutability triggers.")
    add_bullet(doc, "A SECURITY DEFINER function (archive_old_audit_logs() / archive_old_auth_audit()) copies rows older than 12 months to the archive tables, then deletes from the live table.")
    add_bullet(doc, "A pg_cron job runs every Sunday at 02:00 UTC: SELECT cron.schedule('archive-old-audit-logs', '0 2 * * 0', ...)")

    add_heading(doc, "15.5 Compliance Framework Coverage", 2)
    compliance_data = [
        ["Framework",           "Requirement",                               "Implementation"],
        ["EU AI Act Art.12/13", "Immutable, traceable AI decision logs",     "Immutability triggers + integrity_hash"],
        ["EU AI Act Art.12",    "Retain logs >= 6 months",                   "pg_cron archival — rows never deleted"],
        ["SOC2 CC7.2",          "No unauthorized modification",              "DB triggers block all UPDATE/DELETE"],
        ["SOC2 CC9.1",          "Complete and accurate audit trail",         "ip_address + user_agent + integrity_hash"],
        ["NAIC AI Bulletin",    "Full AI decision audit trail",              "approve_pod/reject_pod logged with details"],
        ["NAIC AI Bulletin",    "Available for regulatory review",           "audit_logs_archive retained indefinitely"],
    ]
    add_table(doc, compliance_data, col_widths_cm=[4.5, 6.0, 6.5])

    add_hr(doc)
    footer = doc.add_paragraph(
        "This document was auto-generated from the Fideon OS codebase. "
        "All diagrams are drawn from live source code analysis. Generated on 2026-03-16."
    )
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].italic = True
    footer.runs[0].font.size = Pt(8)

    doc.save(DOCX_PATH)
    return DOCX_PATH


if __name__ == "__main__":
    # Ensure diagram images exist
    if not os.path.isdir(IMG_DIR) or not os.listdir(IMG_DIR):
        print("ERROR: Diagram images not found in", IMG_DIR)
        print("Run generate_activity_logs_pdf.py first to generate the diagrams.")
        sys.exit(1)
    print("Building Word document...")
    path = build_docx()
    print(f"\nDOCX created: {path}")
