-- Core schema gap closure (backward-compatible)
-- Covers:
-- - app_users.role_id + unique email guarantee
-- - roles.role_id + roles.name compatibility columns
-- - devices.tenant_id + devices.token_hash
-- - audit_logs monthly partitioning
-- - strict public.models table
-- - tenants first-class plan/tier columns

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------------------
-- Roles compatibility columns (role_id, name)
-- -------------------------------------------------------------------
ALTER TABLE public.roles
  ADD COLUMN IF NOT EXISTS role_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.roles
  ADD COLUMN IF NOT EXISTS name TEXT;

UPDATE public.roles
SET name = role::text
WHERE name IS NULL;

UPDATE public.roles
SET role_id = nextval(pg_get_serial_sequence('public.roles', 'role_id'))
WHERE role_id IS NULL;

ALTER TABLE public.roles
  ALTER COLUMN role_id SET NOT NULL;

ALTER TABLE public.roles
  ALTER COLUMN name SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_role_id ON public.roles(role_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_roles_name ON public.roles(name);

-- -------------------------------------------------------------------
-- app_users role_id + unique email at DB level
-- -------------------------------------------------------------------
ALTER TABLE public.app_users
  ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES public.roles(role_id) ON DELETE SET NULL;

UPDATE public.app_users au
SET role_id = r.role_id
FROM public.user_roles ur
JOIN public.roles r ON r.role = ur.role
WHERE au.user_id = ur.user_id
  AND au.role_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_app_users_role_id ON public.app_users(role_id);

-- Enforce uniqueness on normalized non-empty emails.
CREATE UNIQUE INDEX IF NOT EXISTS uq_app_users_email_normalized
  ON public.app_users (lower(trim(email)))
  WHERE email IS NOT NULL AND length(trim(email)) > 0;

-- Keep app_users.role_id synchronized from canonical user_roles assignments.
CREATE OR REPLACE FUNCTION public.sync_app_user_role_id_from_user_roles()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  resolved_role_id BIGINT;
BEGIN
  SELECT r.role_id
    INTO resolved_role_id
    FROM public.roles r
   WHERE r.role = NEW.role
   LIMIT 1;

  UPDATE public.app_users au
     SET role_id = resolved_role_id
   WHERE au.user_id = NEW.user_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_app_user_role_id_from_user_roles ON public.user_roles;
CREATE TRIGGER trg_sync_app_user_role_id_from_user_roles
  AFTER INSERT OR UPDATE OF role ON public.user_roles
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_app_user_role_id_from_user_roles();

-- -------------------------------------------------------------------
-- Tenants first-class plan/tier columns
-- -------------------------------------------------------------------
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS plan TEXT,
  ADD COLUMN IF NOT EXISTS tier TEXT;

UPDATE public.tenants
SET plan = COALESCE(NULLIF(metadata ->> 'plan', ''), plan, 'free')
WHERE plan IS NULL;

UPDATE public.tenants
SET tier = COALESCE(NULLIF(metadata ->> 'tier', ''), NULLIF(plan, ''), tier, 'free')
WHERE tier IS NULL;

ALTER TABLE public.tenants
  ALTER COLUMN plan SET DEFAULT 'free',
  ALTER COLUMN tier SET DEFAULT 'free';

ALTER TABLE public.tenants
  ALTER COLUMN plan SET NOT NULL,
  ALTER COLUMN tier SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tenants_plan ON public.tenants(plan);
CREATE INDEX IF NOT EXISTS idx_tenants_tier ON public.tenants(tier);

-- -------------------------------------------------------------------
-- Strict public.models table with version/gpu/memory/manifest
-- -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id TEXT NOT NULL,
  name TEXT NOT NULL,
  version TEXT NOT NULL DEFAULT '1.0.0',
  gpu TEXT,
  memory TEXT,
  manifest JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (model_id, version)
);

CREATE INDEX IF NOT EXISTS idx_models_model_id ON public.models(model_id);
CREATE INDEX IF NOT EXISTS idx_models_is_active ON public.models(is_active);

INSERT INTO public.models (model_id, name, version, manifest, is_active)
SELECT
  mc.model_id,
  mc.model_name,
  '1.0.0',
  jsonb_strip_nulls(
    jsonb_build_object(
      'provider', mc.provider,
      'domain', mc.domain,
      'description', mc.description,
      'metadata', COALESCE(mc.metadata, '{}'::jsonb)
    )
  ),
  mc.is_active
FROM public.model_catalog mc
ON CONFLICT (model_id, version) DO UPDATE
SET
  name = EXCLUDED.name,
  manifest = EXCLUDED.manifest,
  is_active = EXCLUDED.is_active;

DROP TRIGGER IF EXISTS update_models_updated_at ON public.models;
CREATE TRIGGER update_models_updated_at
  BEFORE UPDATE ON public.models
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.models ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view models" ON public.models;
CREATE POLICY "Authenticated users can view models"
  ON public.models
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Admins can manage models" ON public.models;
CREATE POLICY "Admins can manage models"
  ON public.models
  FOR ALL
  USING (public.has_role(auth.uid(), 'admin'::public.app_role))
  WITH CHECK (public.has_role(auth.uid(), 'admin'::public.app_role));

-- -------------------------------------------------------------------
-- Devices: tenant_id + token_hash compatibility
-- -------------------------------------------------------------------
ALTER TABLE public.devices
  ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES public.tenants(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS token_hash TEXT;

UPDATE public.devices d
SET tenant_id = au.tenant_id
FROM public.app_users au
WHERE d.tenant_id IS NULL
  AND d.registered_by = au.user_id;

UPDATE public.devices
SET token_hash = encode(extensions.digest(convert_to(device_token, 'UTF8'), 'sha256'::text), 'hex')
WHERE token_hash IS NULL
  AND device_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_devices_tenant_id ON public.devices(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_devices_token_hash
  ON public.devices(token_hash)
  WHERE token_hash IS NOT NULL;

CREATE OR REPLACE FUNCTION public.devices_set_derived_columns()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.device_token IS NOT NULL THEN
    NEW.token_hash := encode(extensions.digest(convert_to(NEW.device_token, 'UTF8'), 'sha256'::text), 'hex');
  END IF;

  IF NEW.tenant_id IS NULL AND NEW.registered_by IS NOT NULL THEN
    SELECT au.tenant_id
      INTO NEW.tenant_id
      FROM public.app_users au
     WHERE au.user_id = NEW.registered_by
     LIMIT 1;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_devices_set_derived_columns ON public.devices;
CREATE TRIGGER trg_devices_set_derived_columns
  BEFORE INSERT OR UPDATE OF device_token, registered_by, tenant_id ON public.devices
  FOR EACH ROW
  EXECUTE FUNCTION public.devices_set_derived_columns();

-- -------------------------------------------------------------------
-- audit_logs monthly partitioning
-- -------------------------------------------------------------------
DO $$
DECLARE
  audit_is_partitioned BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'audit_logs'
  ) INTO audit_is_partitioned;

  IF NOT audit_is_partitioned THEN
    ALTER TABLE public.audit_logs RENAME TO audit_logs_legacy;

    CREATE TABLE public.audit_logs (
      LIKE public.audit_logs_legacy INCLUDING DEFAULTS INCLUDING GENERATED INCLUDING STORAGE INCLUDING COMMENTS EXCLUDING CONSTRAINTS
    ) PARTITION BY RANGE (created_at);

    -- Partitioned tables cannot enforce uniqueness/PK unless partition key is included.
    ALTER TABLE public.audit_logs
      ADD CONSTRAINT audit_logs_pk PRIMARY KEY (created_at, id);

    CREATE TABLE IF NOT EXISTS public.audit_logs_default PARTITION OF public.audit_logs DEFAULT;

    -- Recreate indexes as partitioned indexes on the parent.
    CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON public.audit_logs(user_id);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_type ON public.audit_logs(resource_type);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_id ON public.audit_logs(id);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_resource_id
      ON public.audit_logs(resource_id)
      WHERE resource_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_audit_logs_sequence_num
      ON public.audit_logs(sequence_num DESC);
    CREATE INDEX IF NOT EXISTS idx_audit_logs_model_id
      ON public.audit_logs(model_id)
      WHERE model_id IS NOT NULL;

    ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

    DROP POLICY IF EXISTS "Admins can view all audit logs" ON public.audit_logs;
    CREATE POLICY "Admins can view all audit logs"
      ON public.audit_logs
      FOR SELECT
      USING (public.has_role(auth.uid(), 'admin'::public.app_role));

    DROP POLICY IF EXISTS "Users can view own audit logs" ON public.audit_logs;
    CREATE POLICY "Users can view own audit logs"
      ON public.audit_logs
      FOR SELECT
      USING (auth.uid() = user_id);

    DROP POLICY IF EXISTS "Authenticated users can insert own audit logs" ON public.audit_logs;
    CREATE POLICY "Authenticated users can insert own audit logs"
      ON public.audit_logs
      FOR INSERT
      WITH CHECK (
        auth.uid() IS NOT NULL
        AND (
          user_id IS NULL
          OR user_id = auth.uid()
          OR public.has_role(auth.uid(), 'admin'::public.app_role)
        )
      );

    DROP TRIGGER IF EXISTS audit_logs_no_update ON public.audit_logs;
    CREATE TRIGGER audit_logs_no_update
      BEFORE UPDATE ON public.audit_logs
      FOR EACH ROW
      EXECUTE FUNCTION public.prevent_audit_modification();

    DROP TRIGGER IF EXISTS audit_logs_no_delete ON public.audit_logs;
    CREATE TRIGGER audit_logs_no_delete
      BEFORE DELETE ON public.audit_logs
      FOR EACH ROW
      EXECUTE FUNCTION public.prevent_audit_modification();

    DROP TRIGGER IF EXISTS audit_logs_chain_hash ON public.audit_logs;
    CREATE TRIGGER audit_logs_chain_hash
      BEFORE INSERT ON public.audit_logs
      FOR EACH ROW
      EXECUTE FUNCTION public.compute_audit_chain_hash();

    INSERT INTO public.audit_logs
    OVERRIDING SYSTEM VALUE
    SELECT * FROM public.audit_logs_legacy;

    PERFORM setval(
      pg_get_serial_sequence('public.audit_logs', 'sequence_num'),
      COALESCE((SELECT MAX(sequence_num) FROM public.audit_logs), 1),
      true
    );

    DROP TABLE public.audit_logs_legacy;
  END IF;
END;
$$;

-- Create monthly partitions for 12 months back + 24 months forward.
DO $$
DECLARE
  audit_is_partitioned BOOLEAN;
  month_start DATE;
  month_end DATE;
  partition_name TEXT;
  i INTEGER;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'audit_logs'
  ) INTO audit_is_partitioned;

  IF audit_is_partitioned THEN
    FOR i IN -12..24 LOOP
      month_start := (date_trunc('month', CURRENT_DATE) + (i || ' month')::interval)::date;
      month_end := (date_trunc('month', CURRENT_DATE) + ((i + 1) || ' month')::interval)::date;
      partition_name := format('audit_logs_%s', to_char(month_start, 'YYYYMM'));

      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.audit_logs FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        month_start,
        month_end
      );
    END LOOP;
  END IF;
END;
$$;
